Add basic support for OpenSUSE

diff --git a/setup-bingcc b/setup-bingcc
--- a/setup-bingcc
+++ b/setup-bingcc
@@ -10,6 +10,15 @@ elif [ -f /etc/redhat-release ] ; then
 	# Red Hat / CentOS / Sci Linux are the same as fedora
 	LIBCPATH="/lib64/libc.so.6 /lib64/libm.so.6 /lib/librt.so.1"
 	LIBC32PATH="/lib/libc.so.6 /lib/libm.so.6 /lib/librt.so.1"
+elif [ -e /etc/os-release ] ; then
+	. /etc/os-release
+	if [[ "$ID_LIKE" = *"suse"* ]] ; then
+		LIBCPATH="/lib64/libc.so.6 /lib64/libm.so.6 /lib/librt.so.1"
+		LIBC32PATH="/lib/libc.so.6 /lib/libm.so.6 /lib/librt.so.1"
+	else
+		echo "Could not find settings for your distro (${ID_LIKE})."
+		exit 1
+	fi
 else
 	echo "Could not find settings for your distro!"
 	exit 1
